#ifndef __IOCONFIG_H__
#define __IOCONFIG_H__

#ifdef __cplusplus
extern "C" {
#endif

#include "n32wb452.h"

// LED
#define R_LED_PIN GPIO_PIN_13
#define R_LED_GPIO GPIOC
#define G_LED_PIN GPIO_PIN_11
#define G_LED_GPIO GPIOA

// I2C
#define I2C1_SCL_PIN GPIO_PIN_6
#define I2C1_SCL_GPIO GPIOB
#define I2C1_SDA_PIN GPIO_PIN_7
#define I2C1_SDA_GPIO GPIOB

#define I2C2_SCL_PIN GPIO_PIN_10
#define I2C2_SCL_GPIO GPIOB
#define I2C2_SDA_PIN GPIO_PIN_11
#define I2C2_SDA_GPIO GPIOB

// 电路切换 置低位UART3, 置高位I2C2
#define CIRCUIT_SWITCH_PIN GPIO_PIN_3
#define CIRCUIT_SWITCH_GPIO GPIOB

#define CIRCUIT_SWITCH_UART3_ON() GPIO_ResetBits(CIRCUIT_SWITCH_GPIO, CIRCUIT_SWITCH_PIN)
#define CIRCUIT_SWITCH_I2C2_ON() GPIO_SetBits(CIRCUIT_SWITCH_GPIO, CIRCUIT_SWITCH_PIN)

// 串口
#define UART2_TX_PIN GPIO_PIN_4
#define UART2_TX_GPIO GPIOB
#define UART2_RX_PIN GPIO_PIN_5
#define UART2_RX_GPIO GPIOB

#define UART3_TX_PIN GPIO_PIN_10
#define UART3_TX_GPIO GPIOB
#define UART3_RX_PIN GPIO_PIN_11
#define UART3_RX_GPIO GPIOB

/* SPI */ 
// 屏幕
#define SRC_SCL_PIN GPIO_PIN_5
#define SRC_SCL_GPIO GPIOA
#define SRC_DC_PIN GPIO_PIN_6
#define SRC_DC_GPIO GPIOA
#define SRC_SDA_PIN GPIO_PIN_7
#define SRC_SDA_GPIO GPIOA
#define SRC_CS_PIN GPIO_PIN_4
#define SRC_CS_GPIO GPIOA
#define SRC_RES_PIN GPIO_PIN_2
#define SRC_RES_GPIO GPIOB
#define SRC_LEDA_PIN GPIO_PIN_11
#define SRC_LEDA_GPIO GPIOA

// flash
#define SPI2_SCK_PIN GPIO_PIN_13
#define SPI2_SCK_GPIO GPIOB
#define SPI2_MISO_PIN GPIO_PIN_14
#define SPI2_MISO_GPIO GPIOB
#define SPI2_MOSI_PIN GPIO_PIN_15
#define SPI2_MOSI_GPIO GPIOB
#define SPI2_NSS_PIN GPIO_PIN_12
#define SPI2_NSS_GPIO GPIOB


#ifdef __cplusplus
}
#endif

#endif /* __IOCONFIG_H__ */
/**
 * @}
 */
