# 导入构建相关函数
from building import *
import os

# 获取当前目录路径
cwd = GetCurrentDir()
# 设置C/C++头文件搜索路径为当前目录
CPPPATH = [cwd]

# 获取当前目录下所有.c源文件
src = Glob('*.c')

#获取指定的.c源文件：
# src = ['shell.c', 'msh.c']
# if GetDepend('MSH_USING_BUILT_IN_COMMANDS'): # 判断是否启用MSH的内建命令
# src += ['cmd.c']



# 使用 DefineGroup 创建一个名为 Hardware 的组
# 该Group是否被添加到工程中，参与编译，取决于depend的宏是否在Kconfig中被使能。
# group = DefineGroup('Hardware', src, depend = ['USE_HARDWARE_ENLBLE'], CPPPATH = CPPPATH)
# 即上述的头文件路径和C文件是否被编译，取决于用户在Kconfig中是否使能了RT_USING_FINSH
group = DefineGroup('Hardware', src, depend = [''], CPPPATH = CPPPATH)

# 获取当前目录下的所有文件和文件夹列表
list = os.listdir(cwd)
# 遍历所有子目录
for item in list:
    # 检查子目录下是否存在SConscript文件
    if os.path.isfile(os.path.join(cwd, item, 'SConscript')):
        # 如果存在，则递归调用该SConscript文件并将其返回的组添加到当前组中
        group = group + SConscript(os.path.join(item, 'SConscript'))

# 返回构建组给上级SConscript文件
Return('group')